Libararies

In [27]:
from pathlib import Path
import pandas as pd
import numpy as np
import os

import sys
sys.path.append("/Users/jackguptill/Library/CloudStorage/OneDrive-Personal/Code/F1FantasyProject")

import teamOptimizer as to

### File Import

In [33]:
working_directory = Path.cwd().parent.parent
print(working_directory)


#FIXME: consider not having these vals hardcoded or wrapping in a read function that
#  has the ability to do both hard coded or default most recent week

file_path_drivers = working_directory / "data" / "predictions" / "drivers" / "driver_predictions_2026.csv" 
file_path_constr = working_directory / "data" / "predictions" / "constructors" / "constructor_preds_2026.csv"
file_path_roster = working_directory / "data" / "myTeam" / "teamConfig.csv"

predicted_points_constr = pd.read_csv(file_path_constr).drop(columns=["Unnamed: 0"])
predicted_points_drivers = pd.read_csv(file_path_drivers)

last_week_roster = pd.read_csv(file_path_roster).drop(columns=["Unnamed: 0"])

/Users/jackguptill/Library/CloudStorage/OneDrive-Personal/Code/F1FantasyProject

### Filter the predicted points to the max race of the max year

In [34]:
year = max(predicted_points_drivers["year"])
race = max(predicted_points_drivers["race_num"])
print(year, race)

2026 2

In [35]:
predicted_points_constr = predicted_points_constr[(predicted_points_constr["year"] == year) & (predicted_points_constr["race_num"] == race)]
predicted_points_drivers = predicted_points_drivers[(predicted_points_drivers["year"] == year) & (predicted_points_drivers["race_num"] == race)]
#need this to be the prior week so 1- current week #FIXME: will this break when there is a 2 or three week gap between races?
last_week_roster = last_week_roster[(last_week_roster["race"] == race-1) & (last_week_roster["year"] == year)]

In [36]:
predicted_points_constr.head()

    year  race_num constructor  price  predicted_points
11  2026         2         mer   29.6         74.524806
12  2026         2         rbr   28.5         55.433908
13  2026         2         fer   23.6         53.293950
14  2026         2         mcl   28.8         45.272810
15  2026         2          rb    6.9         27.702746

In [37]:
predicted_points_drivers.head()

    year  race_num driver  price constructor  predicted_points
22  2026         2    VER   28.0         RBR         39.337494
23  2026         2    RUS   27.7         MER         33.828518
24  2026         2    NOR   27.1         MCL         22.145670
25  2026         2    PIA   25.2         MCL         22.028571
26  2026         2    ANT   23.5         MER         11.566829

In [38]:
last_week_roster.head()

,Race_team,year,race,constructor_1,constructor_2,driver_1,driver_2,driver_3,driver_4,driver_5,bonus_driver,team
0,1_Guppies,2026,1,FER,RB,VER,LEC,HUL,COL,LAW,VER,Guppies
1,1_Guppies2,2026,1,MCL,RB,VER,HAD,HUL,COL,LAW,VER,Guppies2

In [25]:
drivers_sel, cons_sel, summary = to.optimize_team(
    budget=100,
    drivers=predicted_points_drivers,
    cons=predicted_points_constr,
    points_col="predicted_points",
    n_drivers=5,
    n_constructors=2,
    max_drivers_per_team=2,
    use_drs=True,
    drs_multiplier=2.0,
    solver_msg=False,
    require_driver_from_each_constructor=False,
    min_drivers_per_selected_constructor=1
)

print(summary)
display(drivers_sel)
display(cons_sel)

{'status': 1, 'budget': 100, 'points_column_used': 'predicted_points', 'total_price': 97.2, 'total_points': 213.26, 'drs_driver': 'VER'}

   year  race_num driver  price constructor  predicted_points team_key
0  2026         2    VER   28.0         RBR         39.337494      RBR
1  2026         2    STR    7.4         AMR         10.322223      AMR
2  2026         2    BEA    8.0         HAS          8.392114      HAS
3  2026         2    OCO    7.9         HAS          7.269343      HAS
4  2026         2    ALO    9.4         AMR          6.369600      AMR

   year  race_num constructor  price  predicted_points team_key
0  2026         2         mer   29.6         74.524806      MER
1  2026         2          rb    6.9         27.702746       RB