In [6]:
import duckdb
from pathlib import Path

In [7]:
working_directory = Path.cwd().parent.parent
DATABASE_PATH = working_directory / "data" / "database" / "f1_fantasy.duckdb"

### Meetings Table

In [8]:

def read_raw_meetings_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_meetings_table").df()

    return result

In [9]:
raw_query = read_raw_meetings_table()
raw_query

,meeting_key,meeting_name,meeting_official_name,location,country_key,country_code,country_name,country_flag,circuit_key,circuit_short_name,circuit_type,circuit_info_url,circuit_image,gmt_offset,date_start,date_end,year
0,1140,Pre-Season Testing,FORMULA 1 ARAMCO PRE-SEASON TESTING 2023,Sakhir,36,BRN,Bahrain,https://media.formula1.com/content/dam/fom-web...,63,Sakhir,Permanent,https://api.multiviewer.app/api/v1/circuits/63...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2023-02-23T07:00:00+00:00,2023-02-25T16:30:00+00:00,2023
1,1141,Bahrain Grand Prix,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023,Sakhir,36,BRN,Bahrain,https://media.formula1.com/content/dam/fom-web...,63,Sakhir,Permanent,https://api.multiviewer.app/api/v1/circuits/63...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2023-03-03T11:30:00+00:00,2023-03-05T17:00:00+00:00,2023
2,1142,Saudi Arabian Grand Prix,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2023,Jeddah,153,KSA,Saudi Arabia,https://media.formula1.com/content/dam/fom-web...,149,Jeddah,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/14...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2023-03-17T13:30:00+00:00,2023-03-19T19:00:00+00:00,2023
3,1143,Australian Grand Prix,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2023,Melbourne,5,AUS,Australia,https://media.formula1.com/content/dam/fom-web...,10,Melbourne,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/10...,https://media.formula1.com/content/dam/fom-web...,10:00:00,2023-03-31T02:30:00+00:00,2023-04-02T07:00:00+00:00,2023
4,1207,Azerbaijan Grand Prix,FORMULA 1 AZERBAIJAN GRAND PRIX 2023,Baku,30,AZE,Azerbaijan,https://media.formula1.com/content/dam/fom-web...,144,Baku,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/14...,https://media.formula1.com/content/dam/fom-web...,04:00:00,2023-04-28T09:30:00+00:00,2023-04-30T13:00:00+00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,1298,Mexico City Grand Prix,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026,Mexico City,8,MEX,Mexico,https://media.formula1.com/content/dam/fom-web...,65,Mexico City,Permanent,https://api.multiviewer.app/api/v1/circuits/65...,https://media.formula1.com/content/dam/fom-web...,-06:00:00,2026-10-30T18:30:00+00:00,2026-11-01T22:00:00+00:00,2026
122,1299,São Paulo Grand Prix,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,São Paulo,10,BRA,Brazil,https://media.formula1.com/content/dam/fom-web...,14,Interlagos,Permanent,https://api.multiviewer.app/api/v1/circuits/14...,https://media.formula1.com/content/dam/fom-web...,-03:00:00,2026-11-06T15:30:00+00:00,2026-11-08T19:00:00+00:00,2026
123,1300,Las Vegas Grand Prix,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026,Las Vegas,19,USA,United States,https://media.formula1.com/content/dam/fom-web...,152,Las Vegas,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/15...,https://media.formula1.com/content/dam/fom-web...,-08:00:00,2026-11-20T00:30:00+00:00,2026-11-22T06:00:00+00:00,2026
124,1301,Qatar Grand Prix,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026,Lusail,149,QAT,Qatar,https://media.formula1.com/content/dam/fom-web...,150,Lusail,Permanent,https://api.multiviewer.app/api/v1/circuits/15...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2026-11-27T13:30:00+00:00,2026-11-29T18:00:00+00:00,2026
125,1302,Abu Dhabi Grand Prix,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,Yas Marina,21,UAE,United Arab Emirates,https://media.formula1.com/content/dam/fom-web...,70,Yas Marina Circuit,Permanent,https://api.multiviewer.app/api/v1/circuits/70...,https://media.formula1.com/content/dam/fom-web...,04:00:00,2026-12-04T09:30:00+00:00,2026-12-06T15:00:00+00:00,2026

In [10]:
raw_query.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   meeting_key            126 non-null    int64
 1   meeting_name           126 non-null    object
 2   meeting_official_name  126 non-null    object
 3   location               126 non-null    object
 4   country_key            126 non-null    int64
 5   country_code           126 non-null    object
 6   country_name           126 non-null    object
 7   country_flag           126 non-null    object
 8   circuit_key            126 non-null    int64
 9   circuit_short_name     126 non-null    object
 10  circuit_type           126 non-null    object
 11  circuit_info_url       126 non-null    object
 12  circuit_image          126 non-null    object
 13  gmt_offset             126 non-null    object
 14  date_start             126 non-null    object
 15  date_end               126 non-null    object
 16  year                   126 non-null    int64
dtypes: int64(4), object(13)
memory usage: 16.9+ KB

In [11]:
def read_staged_meetings_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_race_meetings_table").df()

    return result

In [12]:
staged_query = read_staged_meetings_table()
staged_query

,meeting_key,meeting_name,country_name,circuit_short_name,circuit_type,date_start,date_end,year
0,1141,Bahrain Grand Prix,Bahrain,Sakhir,Permanent,2023-03-03 06:30:00-05:00,2023-03-03 06:30:00-05:00,2023
1,1142,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah,Temporary - Street,2023-03-17 09:30:00-04:00,2023-03-17 09:30:00-04:00,2023
2,1143,Australian Grand Prix,Australia,Melbourne,Temporary - Street,2023-03-30 22:30:00-04:00,2023-03-30 22:30:00-04:00,2023
3,1207,Azerbaijan Grand Prix,Azerbaijan,Baku,Temporary - Street,2023-04-28 05:30:00-04:00,2023-04-28 05:30:00-04:00,2023
4,1208,Miami Grand Prix,United States,Miami,Temporary - Street,2023-05-05 14:00:00-04:00,2023-05-05 14:00:00-04:00,2023
...,...,...,...,...,...,...,...,...
89,1298,Mexico City Grand Prix,Mexico,Mexico City,Permanent,2026-10-30 14:30:00-04:00,2026-10-30 14:30:00-04:00,2026
90,1299,São Paulo Grand Prix,Brazil,Interlagos,Permanent,2026-11-06 10:30:00-05:00,2026-11-06 10:30:00-05:00,2026
91,1300,Las Vegas Grand Prix,United States,Las Vegas,Temporary - Street,2026-11-19 19:30:00-05:00,2026-11-19 19:30:00-05:00,2026
92,1301,Qatar Grand Prix,Qatar,Lusail,Permanent,2026-11-27 08:30:00-05:00,2026-11-27 08:30:00-05:00,2026
93,1302,Abu Dhabi Grand Prix,United Arab Emirates,Yas Marina Circuit,Permanent,2026-12-04 04:30:00-05:00,2026-12-04 04:30:00-05:00,2026

In [13]:
staged_query.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   meeting_key         94 non-null     int64
 1   meeting_name        94 non-null     object
 2   country_name        94 non-null     object
 3   circuit_short_name  94 non-null     object
 4   circuit_type        94 non-null     object
 5   date_start          94 non-null     datetime64[us, America/New_York]
 6   date_end            94 non-null     datetime64[us, America/New_York]
 7   year                94 non-null     int64
dtypes: datetime64[us, America/New_York](2), int64(2), object(4)
memory usage: 6.0+ KB

### Sessions Table

In [14]:
def read_raw_sessions_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_sessions_table").df()

    return result

In [15]:
raw_query = read_raw_sessions_table()
raw_query

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year
0,9222,Practice,Day 1,2023-02-23T07:00:00+00:00,2023-02-23T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
1,7763,Practice,Day 2,2023-02-24T07:00:00+00:00,2023-02-24T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
2,7764,Practice,Day 3,2023-02-25T07:00:00+00:00,2023-02-25T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
3,7765,Practice,Practice 1,2023-03-03T11:30:00+00:00,2023-03-03T12:30:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
4,7766,Practice,Practice 2,2023-03-03T15:00:00+00:00,2023-03-03T16:00:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,11429,Practice,Practice 1,2026-12-04T09:30:00+00:00,2026-12-04T10:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
612,11430,Practice,Practice 2,2026-12-04T13:00:00+00:00,2026-12-04T14:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
613,11431,Practice,Practice 3,2026-12-05T10:30:00+00:00,2026-12-05T11:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
614,11432,Qualifying,Qualifying,2026-12-05T14:00:00+00:00,2026-12-05T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
615,11436,Race,Race,2026-12-06T13:00:00+00:00,2026-12-06T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026

In [16]:
def read_staged_sessions_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_race_sessions_table").df()

    return result

In [17]:
staged_query = read_raw_sessions_table()
staged_query

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year
0,9222,Practice,Day 1,2023-02-23T07:00:00+00:00,2023-02-23T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
1,7763,Practice,Day 2,2023-02-24T07:00:00+00:00,2023-02-24T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
2,7764,Practice,Day 3,2023-02-25T07:00:00+00:00,2023-02-25T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
3,7765,Practice,Practice 1,2023-03-03T11:30:00+00:00,2023-03-03T12:30:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
4,7766,Practice,Practice 2,2023-03-03T15:00:00+00:00,2023-03-03T16:00:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,11429,Practice,Practice 1,2026-12-04T09:30:00+00:00,2026-12-04T10:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
612,11430,Practice,Practice 2,2026-12-04T13:00:00+00:00,2026-12-04T14:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
613,11431,Practice,Practice 3,2026-12-05T10:30:00+00:00,2026-12-05T11:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
614,11432,Qualifying,Qualifying,2026-12-05T14:00:00+00:00,2026-12-05T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
615,11436,Race,Race,2026-12-06T13:00:00+00:00,2026-12-06T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026

### Drivers Table

In [18]:
def read_raw_drivers_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_drivers_table").df()

    return result

In [19]:
raw_query = read_raw_drivers_table()

raw_query

,meeting_key,session_key,driver_number,broadcast_name,full_name,name_acronym,team_name,team_colour,first_name,last_name,headshot_url,country_code
0,1140,7763,1,M VERSTAPPEN,Max VERSTAPPEN,VER,Red Bull Racing,3671C6,Max,Verstappen,https://www.formula1.com/content/dam/fom-websi...,NED
1,1140,7763,2,L SARGEANT,Logan SARGEANT,SAR,Williams,37BEDD,Logan,Sargeant,https://www.formula1.com/content/dam/fom-websi...,USA
2,1140,7763,4,L NORRIS,Lando NORRIS,NOR,McLaren,F58020,Lando,Norris,https://www.formula1.com/content/dam/fom-websi...,GBR
3,1140,7763,10,P GASLY,Pierre GASLY,GAS,Alpine,2293D1,Pierre,Gasly,https://www.formula1.com/content/dam/fom-websi...,FRA
4,1140,7763,11,S PEREZ,Sergio PEREZ,PER,Red Bull Racing,3671C6,Sergio,Perez,https://www.formula1.com/content/dam/fom-websi...,MEX
...,...,...,...,...,...,...,...,...,...,...,...,...
9946,1302,11436,55,C SAINZ,Carlos SAINZ,SAI,Williams,1868DB,Carlos,Sainz,https://media.formula1.com/d_driver_fallback_i...,None
9947,1302,11436,63,G RUSSELL,George RUSSELL,RUS,Mercedes,00D7B6,George,Russell,https://media.formula1.com/d_driver_fallback_i...,None
9948,1302,11436,77,V BOTTAS,Valtteri BOTTAS,BOT,Cadillac,909090,Valtteri,Bottas,https://media.formula1.com/d_driver_fallback_i...,None
9949,1302,11436,81,O PIASTRI,Oscar PIASTRI,PIA,McLaren,F47600,Oscar,Piastri,https://media.formula1.com/d_driver_fallback_i...,None
9950,1302,11436,87,O BEARMAN,Oliver BEARMAN,BEA,Haas F1 Team,9C9FA2,Oliver,Bearman,https://media.formula1.com/d_driver_fallback_i...,None

In [20]:
def read_staged_drivers_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_session_drivers_table").df()

    return result

In [21]:
staged_drivers = read_staged_drivers_table()
staged_drivers

,meeting_key,session_key,driver_number,full_name,name_acronym,team_name,first_name,last_name
0,1140,7763,1,Max VERSTAPPEN,VER,Red Bull Racing,Max,Verstappen
1,1140,7763,2,Logan SARGEANT,SAR,Williams,Logan,Sargeant
2,1140,7763,4,Lando NORRIS,NOR,McLaren,Lando,Norris
3,1140,7763,10,Pierre GASLY,GAS,Alpine,Pierre,Gasly
4,1140,7763,11,Sergio PEREZ,PER,Red Bull Racing,Sergio,Perez
...,...,...,...,...,...,...,...,...
9945,1302,11436,55,Carlos SAINZ,SAI,Williams,Carlos,Sainz
9946,1302,11436,63,George RUSSELL,RUS,Mercedes,George,Russell
9947,1302,11436,77,Valtteri BOTTAS,BOT,Cadillac,Valtteri,Bottas
9948,1302,11436,81,Oscar PIASTRI,PIA,McLaren,Oscar,Piastri
9949,1302,11436,87,Oliver BEARMAN,BEA,Haas F1 Team,Oliver,Bearman

In [22]:
cols= ["meeting_key", "session_key", "full_name"]

duplicates = staged_drivers.duplicated(subset=cols, keep=False)

duplicates

0       False
1       False
2       False
3       False
4       False
        ...
9945    False
9946    False
9947    False
9948    False
9949    False
Length: 9950, dtype: bool

In [23]:
def read_drivers_dim_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM dim_driver").df()

    return result

In [24]:
drivers = read_drivers_dim_table()
drivers

    driver_id       driver_name name_acronym
0           1  Alejandro GARCIA          GAR
1           2   Alexander ALBON          ALB
2           3   Alexander DUNNE          DUN
3           4     Antonio FUOCO          FUO
4           5    Arthur LECLERC          LEL
..        ...               ...          ...
66         67    Victor MARTINS          MAR
67         68      Woohyun SHIN          SHI
68         69      Yuki TSUNODA          TSU
69         70       ZHOU Guanyu          ZHO
70         71    Zak O'SULLIVAN          OSU

[71 rows x 3 columns]

In [ ]:
#drivers.to_csv("drivers_testing_4_16_2.csv")

### Constructors

In [26]:
def read_raw_constructors():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_constructor_table").df()

    return result

In [27]:
raw_constructors = read_raw_constructors()
raw_constructors

    constructor_name  year              event_name
0         Alfa Romeo  2023   Azerbaijan Grand Prix
1         Alfa Romeo  2023    Las Vegas Grand Prix
2         Alfa Romeo  2023    São Paulo Grand Prix
3         Alfa Romeo  2023    Hungarian Grand Prix
4         Alfa Romeo  2023     Austrian Grand Prix
..               ...   ...                     ...
728         Williams  2023      Spanish Grand Prix
729         Williams  2025  Mexico City Grand Prix
730         Williams  2023    Singapore Grand Prix
731         Williams  2023  Mexico City Grand Prix
732         Williams  2023        Dutch Grand Prix

[733 rows x 3 columns]

In [34]:
def read_staged_constructors():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_session_constructors_table").df()

    return result

In [35]:
staged_constructors = read_staged_constructors()
staged_constructors

    year constructor_name
0   2023       Alfa Romeo
1   2023       AlphaTauri
2   2023           Alpine
3   2023     Aston Martin
4   2023          Ferrari
5   2023     Haas F1 Team
6   2023          McLaren
7   2023         Mercedes
8   2023  Red Bull Racing
9   2023         Williams
10  2024           Alpine
11  2024     Aston Martin
12  2024          Ferrari
13  2024     Haas F1 Team
14  2024      Kick Sauber
15  2024          McLaren
16  2024         Mercedes
17  2024               RB
18  2024  Red Bull Racing
19  2024         Williams
20  2025           Alpine
21  2025     Aston Martin
22  2025          Ferrari
23  2025     Haas F1 Team
24  2025      Kick Sauber
25  2025          McLaren
26  2025         Mercedes
27  2025     Racing Bulls
28  2025  Red Bull Racing
29  2025         Williams
30  2026           Alpine
31  2026     Aston Martin
32  2026             Audi
33  2026         Cadillac
34  2026          Ferrari
35  2026     Haas F1 Team
36  2026          McLaren
37  2026         Mercedes
38  2026     Racing Bulls
39  2026  Red Bull Racing
40  2026         Williams

In [38]:

def read_warehoused_constructors():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM dim_constructor").df()

    return result

In [39]:
dim_constructors = read_warehoused_constructors()
dim_constructors

    constructor_id  year constructor_name
0                1  2023       Alfa Romeo
1                2  2023       AlphaTauri
2                3  2023           Alpine
3                4  2024           Alpine
4                5  2025           Alpine
5                6  2026           Alpine
6                7  2023     Aston Martin
7                8  2024     Aston Martin
8                9  2025     Aston Martin
9               10  2026     Aston Martin
10              11  2026             Audi
11              12  2026         Cadillac
12              13  2023          Ferrari
13              14  2024          Ferrari
14              15  2025          Ferrari
15              16  2026          Ferrari
16              17  2023     Haas F1 Team
17              18  2024     Haas F1 Team
18              19  2025     Haas F1 Team
19              20  2026     Haas F1 Team
20              21  2024      Kick Sauber
21              22  2025      Kick Sauber
22              23  2023          McLaren
23              24  2024          McLaren
24              25  2025          McLaren
25              26  2026          McLaren
26              27  2023         Mercedes
27              28  2024         Mercedes
28              29  2025         Mercedes
29              30  2026         Mercedes
30              31  2024               RB
31              32  2025     Racing Bulls
32              33  2026     Racing Bulls
33              34  2023  Red Bull Racing
34              35  2024  Red Bull Racing
35              36  2025  Red Bull Racing
36              37  2026  Red Bull Racing
37              38  2023         Williams
38              39  2024         Williams
39              40  2025         Williams
40              41  2026         Williams

### Race

In [40]:
def read_staged_meetings():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_race_meetings_table").df()

    return result

In [41]:
staged_meetings = read_staged_meetings()
staged_meetings

,meeting_key,meeting_name,country_name,circuit_short_name,circuit_type,date_start,date_end,year
0,1141,Bahrain Grand Prix,Bahrain,Sakhir,Permanent,2023-03-03 06:30:00-05:00,2023-03-03 06:30:00-05:00,2023
1,1142,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah,Temporary - Street,2023-03-17 09:30:00-04:00,2023-03-17 09:30:00-04:00,2023
2,1143,Australian Grand Prix,Australia,Melbourne,Temporary - Street,2023-03-30 22:30:00-04:00,2023-03-30 22:30:00-04:00,2023
3,1207,Azerbaijan Grand Prix,Azerbaijan,Baku,Temporary - Street,2023-04-28 05:30:00-04:00,2023-04-28 05:30:00-04:00,2023
4,1208,Miami Grand Prix,United States,Miami,Temporary - Street,2023-05-05 14:00:00-04:00,2023-05-05 14:00:00-04:00,2023
...,...,...,...,...,...,...,...,...
89,1298,Mexico City Grand Prix,Mexico,Mexico City,Permanent,2026-10-30 14:30:00-04:00,2026-10-30 14:30:00-04:00,2026
90,1299,São Paulo Grand Prix,Brazil,Interlagos,Permanent,2026-11-06 10:30:00-05:00,2026-11-06 10:30:00-05:00,2026
91,1300,Las Vegas Grand Prix,United States,Las Vegas,Temporary - Street,2026-11-19 19:30:00-05:00,2026-11-19 19:30:00-05:00,2026
92,1301,Qatar Grand Prix,Qatar,Lusail,Permanent,2026-11-27 08:30:00-05:00,2026-11-27 08:30:00-05:00,2026
93,1302,Abu Dhabi Grand Prix,United Arab Emirates,Yas Marina Circuit,Permanent,2026-12-04 04:30:00-05:00,2026-12-04 04:30:00-05:00,2026