In [2]:
import duckdb
from pathlib import Path

In [3]:
working_directory = Path.cwd().parent.parent
DATABASE_PATH = working_directory / "data" / "database" / "f1_fantasy.duckdb"

### Meetings Table

In [4]:

def read_raw_meetings_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_meetings_table").df()

    return result

In [5]:
raw_query = read_raw_meetings_table()
raw_query

,meeting_key,meeting_name,meeting_official_name,location,country_key,country_code,country_name,country_flag,circuit_key,circuit_short_name,circuit_type,circuit_info_url,circuit_image,gmt_offset,date_start,date_end,year
0,1140,Pre-Season Testing,FORMULA 1 ARAMCO PRE-SEASON TESTING 2023,Sakhir,36,BRN,Bahrain,https://media.formula1.com/content/dam/fom-web...,63,Sakhir,Permanent,https://api.multiviewer.app/api/v1/circuits/63...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2023-02-23T07:00:00+00:00,2023-02-25T16:30:00+00:00,2023
1,1141,Bahrain Grand Prix,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023,Sakhir,36,BRN,Bahrain,https://media.formula1.com/content/dam/fom-web...,63,Sakhir,Permanent,https://api.multiviewer.app/api/v1/circuits/63...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2023-03-03T11:30:00+00:00,2023-03-05T17:00:00+00:00,2023
2,1142,Saudi Arabian Grand Prix,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2023,Jeddah,153,KSA,Saudi Arabia,https://media.formula1.com/content/dam/fom-web...,149,Jeddah,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/14...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2023-03-17T13:30:00+00:00,2023-03-19T19:00:00+00:00,2023
3,1143,Australian Grand Prix,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2023,Melbourne,5,AUS,Australia,https://media.formula1.com/content/dam/fom-web...,10,Melbourne,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/10...,https://media.formula1.com/content/dam/fom-web...,10:00:00,2023-03-31T02:30:00+00:00,2023-04-02T07:00:00+00:00,2023
4,1207,Azerbaijan Grand Prix,FORMULA 1 AZERBAIJAN GRAND PRIX 2023,Baku,30,AZE,Azerbaijan,https://media.formula1.com/content/dam/fom-web...,144,Baku,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/14...,https://media.formula1.com/content/dam/fom-web...,04:00:00,2023-04-28T09:30:00+00:00,2023-04-30T13:00:00+00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,1298,Mexico City Grand Prix,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026,Mexico City,8,MEX,Mexico,https://media.formula1.com/content/dam/fom-web...,65,Mexico City,Permanent,https://api.multiviewer.app/api/v1/circuits/65...,https://media.formula1.com/content/dam/fom-web...,-06:00:00,2026-10-30T18:30:00+00:00,2026-11-01T22:00:00+00:00,2026
122,1299,São Paulo Grand Prix,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,São Paulo,10,BRA,Brazil,https://media.formula1.com/content/dam/fom-web...,14,Interlagos,Permanent,https://api.multiviewer.app/api/v1/circuits/14...,https://media.formula1.com/content/dam/fom-web...,-03:00:00,2026-11-06T15:30:00+00:00,2026-11-08T19:00:00+00:00,2026
123,1300,Las Vegas Grand Prix,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026,Las Vegas,19,USA,United States,https://media.formula1.com/content/dam/fom-web...,152,Las Vegas,Temporary - Street,https://api.multiviewer.app/api/v1/circuits/15...,https://media.formula1.com/content/dam/fom-web...,-08:00:00,2026-11-20T00:30:00+00:00,2026-11-22T06:00:00+00:00,2026
124,1301,Qatar Grand Prix,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026,Lusail,149,QAT,Qatar,https://media.formula1.com/content/dam/fom-web...,150,Lusail,Permanent,https://api.multiviewer.app/api/v1/circuits/15...,https://media.formula1.com/content/dam/fom-web...,03:00:00,2026-11-27T13:30:00+00:00,2026-11-29T18:00:00+00:00,2026
125,1302,Abu Dhabi Grand Prix,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,Yas Marina,21,UAE,United Arab Emirates,https://media.formula1.com/content/dam/fom-web...,70,Yas Marina Circuit,Permanent,https://api.multiviewer.app/api/v1/circuits/70...,https://media.formula1.com/content/dam/fom-web...,04:00:00,2026-12-04T09:30:00+00:00,2026-12-06T15:00:00+00:00,2026

In [6]:
raw_query.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   meeting_key            126 non-null    int64
 1   meeting_name           126 non-null    object
 2   meeting_official_name  126 non-null    object
 3   location               126 non-null    object
 4   country_key            126 non-null    int64
 5   country_code           126 non-null    object
 6   country_name           126 non-null    object
 7   country_flag           126 non-null    object
 8   circuit_key            126 non-null    int64
 9   circuit_short_name     126 non-null    object
 10  circuit_type           126 non-null    object
 11  circuit_info_url       126 non-null    object
 12  circuit_image          126 non-null    object
 13  gmt_offset             126 non-null    object
 14  date_start             126 non-null    object
 15  date_end               126 non-null    object
 16  year                   126 non-null    int64
dtypes: int64(4), object(13)
memory usage: 16.9+ KB

In [7]:
def read_staged_meetings_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_race_meetings_table").df()

    return result

In [8]:
staged_query = read_staged_meetings_table()
staged_query

,meeting_key,meeting_name,country_name,circuit_short_name,circuit_type,date_start,date_end,year
0,1141,Bahrain Grand Prix,Bahrain,Sakhir,Permanent,2023-03-03 06:30:00-05:00,2023-03-03 06:30:00-05:00,2023
1,1142,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah,Temporary - Street,2023-03-17 09:30:00-04:00,2023-03-17 09:30:00-04:00,2023
2,1143,Australian Grand Prix,Australia,Melbourne,Temporary - Street,2023-03-30 22:30:00-04:00,2023-03-30 22:30:00-04:00,2023
3,1207,Azerbaijan Grand Prix,Azerbaijan,Baku,Temporary - Street,2023-04-28 05:30:00-04:00,2023-04-28 05:30:00-04:00,2023
4,1208,Miami Grand Prix,United States,Miami,Temporary - Street,2023-05-05 14:00:00-04:00,2023-05-05 14:00:00-04:00,2023
...,...,...,...,...,...,...,...,...
89,1298,Mexico City Grand Prix,Mexico,Mexico City,Permanent,2026-10-30 14:30:00-04:00,2026-10-30 14:30:00-04:00,2026
90,1299,São Paulo Grand Prix,Brazil,Interlagos,Permanent,2026-11-06 10:30:00-05:00,2026-11-06 10:30:00-05:00,2026
91,1300,Las Vegas Grand Prix,United States,Las Vegas,Temporary - Street,2026-11-19 19:30:00-05:00,2026-11-19 19:30:00-05:00,2026
92,1301,Qatar Grand Prix,Qatar,Lusail,Permanent,2026-11-27 08:30:00-05:00,2026-11-27 08:30:00-05:00,2026
93,1302,Abu Dhabi Grand Prix,United Arab Emirates,Yas Marina Circuit,Permanent,2026-12-04 04:30:00-05:00,2026-12-04 04:30:00-05:00,2026

In [9]:
staged_query.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   meeting_key         94 non-null     int64
 1   meeting_name        94 non-null     object
 2   country_name        94 non-null     object
 3   circuit_short_name  94 non-null     object
 4   circuit_type        94 non-null     object
 5   date_start          94 non-null     datetime64[us, America/New_York]
 6   date_end            94 non-null     datetime64[us, America/New_York]
 7   year                94 non-null     int64
dtypes: datetime64[us, America/New_York](2), int64(2), object(4)
memory usage: 6.0+ KB

### Sessions Table

In [10]:
def read_raw_sessions_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_sessions_table").df()

    return result

In [11]:
raw_query = read_raw_sessions_table()
raw_query

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year
0,9222,Practice,Day 1,2023-02-23T07:00:00+00:00,2023-02-23T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
1,7763,Practice,Day 2,2023-02-24T07:00:00+00:00,2023-02-24T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
2,7764,Practice,Day 3,2023-02-25T07:00:00+00:00,2023-02-25T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
3,7765,Practice,Practice 1,2023-03-03T11:30:00+00:00,2023-03-03T12:30:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
4,7766,Practice,Practice 2,2023-03-03T15:00:00+00:00,2023-03-03T16:00:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,11429,Practice,Practice 1,2026-12-04T09:30:00+00:00,2026-12-04T10:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
612,11430,Practice,Practice 2,2026-12-04T13:00:00+00:00,2026-12-04T14:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
613,11431,Practice,Practice 3,2026-12-05T10:30:00+00:00,2026-12-05T11:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
614,11432,Qualifying,Qualifying,2026-12-05T14:00:00+00:00,2026-12-05T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
615,11436,Race,Race,2026-12-06T13:00:00+00:00,2026-12-06T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026

In [12]:
def read_staged_sessions_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_race_sessions_table").df()

    return result

In [13]:
staged_query = read_raw_sessions_table()
staged_query

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year
0,9222,Practice,Day 1,2023-02-23T07:00:00+00:00,2023-02-23T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
1,7763,Practice,Day 2,2023-02-24T07:00:00+00:00,2023-02-24T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
2,7764,Practice,Day 3,2023-02-25T07:00:00+00:00,2023-02-25T16:30:00+00:00,1140,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
3,7765,Practice,Practice 1,2023-03-03T11:30:00+00:00,2023-03-03T12:30:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
4,7766,Practice,Practice 2,2023-03-03T15:00:00+00:00,2023-03-03T16:00:00+00:00,1141,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,11429,Practice,Practice 1,2026-12-04T09:30:00+00:00,2026-12-04T10:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
612,11430,Practice,Practice 2,2026-12-04T13:00:00+00:00,2026-12-04T14:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
613,11431,Practice,Practice 3,2026-12-05T10:30:00+00:00,2026-12-05T11:30:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
614,11432,Qualifying,Qualifying,2026-12-05T14:00:00+00:00,2026-12-05T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026
615,11436,Race,Race,2026-12-06T13:00:00+00:00,2026-12-06T15:00:00+00:00,1302,70,Yas Marina Circuit,21,UAE,United Arab Emirates,Yas Marina,04:00:00,2026

### Drivers Table

In [14]:
def read_raw_drivers_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_drivers_table").df()

    return result

In [15]:
raw_query = read_raw_drivers_table()

raw_query

,meeting_key,session_key,driver_number,broadcast_name,full_name,name_acronym,team_name,team_colour,first_name,last_name,headshot_url,country_code
0,1141,7953,1,M VERSTAPPEN,Max VERSTAPPEN,VER,Red Bull Racing,3671C6,Max,Verstappen,https://www.formula1.com/content/dam/fom-websi...,NED
1,1141,7953,2,L SARGEANT,Logan SARGEANT,SAR,Williams,37BEDD,Logan,Sargeant,https://www.formula1.com/content/dam/fom-websi...,USA
2,1141,7953,4,L NORRIS,Lando NORRIS,NOR,McLaren,F58020,Lando,Norris,https://www.formula1.com/content/dam/fom-websi...,GBR
3,1141,7953,10,P GASLY,Pierre GASLY,GAS,Alpine,2293D1,Pierre,Gasly,https://www.formula1.com/content/dam/fom-websi...,FRA
4,1141,7953,11,S PEREZ,Sergio PEREZ,PER,Red Bull Racing,3671C6,Sergio,Perez,https://www.formula1.com/content/dam/fom-websi...,MEX
...,...,...,...,...,...,...,...,...,...,...,...,...
9946,1296,11388,55,C SAINZ,Carlos SAINZ,SAI,Williams,1868DB,Carlos,Sainz,https://media.formula1.com/d_driver_fallback_i...,None
9947,1296,11388,63,G RUSSELL,George RUSSELL,RUS,Mercedes,00D7B6,George,Russell,https://media.formula1.com/d_driver_fallback_i...,None
9948,1296,11388,77,V BOTTAS,Valtteri BOTTAS,BOT,Cadillac,909090,Valtteri,Bottas,https://media.formula1.com/d_driver_fallback_i...,None
9949,1296,11388,81,O PIASTRI,Oscar PIASTRI,PIA,McLaren,F47600,Oscar,Piastri,https://media.formula1.com/d_driver_fallback_i...,None
9950,1296,11388,87,O BEARMAN,Oliver BEARMAN,BEA,Haas F1 Team,9C9FA2,Oliver,Bearman,https://media.formula1.com/d_driver_fallback_i...,None

In [16]:
def read_staged_drivers_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_session_drivers_table").df()

    return result

In [17]:
staged_drivers = read_staged_drivers_table()
staged_drivers

,meeting_key,session_key,driver_number,full_name,name_acronym,team_name,first_name,last_name
0,1141,7953,1,max verstappen,VER,Red Bull Racing,Max,Verstappen
1,1141,7953,2,logan sargeant,SAR,Williams,Logan,Sargeant
2,1141,7953,4,lando norris,NOR,McLaren,Lando,Norris
3,1141,7953,10,pierre gasly,GAS,Alpine,Pierre,Gasly
4,1141,7953,11,sergio perez,PER,Red Bull Racing,Sergio,Perez
...,...,...,...,...,...,...,...,...
9945,1296,11388,55,carlos sainz,SAI,Williams,Carlos,Sainz
9946,1296,11388,63,george russell,RUS,Mercedes,George,Russell
9947,1296,11388,77,valtteri bottas,BOT,Cadillac,Valtteri,Bottas
9948,1296,11388,81,oscar piastri,PIA,McLaren,Oscar,Piastri
9949,1296,11388,87,oliver bearman,BEA,Haas F1 Team,Oliver,Bearman

In [18]:
cols= ["meeting_key", "session_key", "full_name"]

duplicates = staged_drivers.duplicated(subset=cols, keep=False)

duplicates

0       False
1       False
2       False
3       False
4       False
        ...
9945    False
9946    False
9947    False
9948    False
9949    False
Length: 9950, dtype: bool

In [19]:
def read_drivers_dim_table():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM dim_driver").df()

    return result

In [20]:
drivers = read_drivers_dim_table()
drivers

    driver_id       driver_name name_acronym
0           1  alejandro garcia          GAR
1           2   alexander albon          ALB
2           3   alexander dunne          DUN
3           4     antonio fuoco          FUO
4           5    arthur leclerc          LEL
..        ...               ...          ...
66         67    victor martins          MAR
67         68      woohyun shin          SHI
68         69      yuki tsunoda          TSU
69         70    zak o'sullivan          OSU
70         71       zhou guanyu          ZHO

[71 rows x 3 columns]

In [21]:
#drivers.to_csv("drivers_testing_4_16_2.csv")

### Constructors

In [22]:
def read_raw_constructors():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_constructor_table").df()

    return result

In [23]:
raw_constructors = read_raw_constructors()
raw_constructors

    constructor_name  year              event_name
0         Alfa Romeo  2023   Azerbaijan Grand Prix
1         Alfa Romeo  2023    Las Vegas Grand Prix
2         Alfa Romeo  2023    São Paulo Grand Prix
3         Alfa Romeo  2023    Hungarian Grand Prix
4         Alfa Romeo  2023     Austrian Grand Prix
..               ...   ...                     ...
728         Williams  2023      Spanish Grand Prix
729         Williams  2025  Mexico City Grand Prix
730         Williams  2023    Singapore Grand Prix
731         Williams  2023  Mexico City Grand Prix
732         Williams  2023        Dutch Grand Prix

[733 rows x 3 columns]

In [24]:
def read_staged_constructors():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_session_constructors_table").df()

    return result

In [25]:
staged_constructors = read_staged_constructors()
staged_constructors

    year constructor_name
0   2023       Alfa Romeo
1   2023       AlphaTauri
2   2023           Alpine
3   2023     Aston Martin
4   2023          Ferrari
5   2023     Haas F1 Team
6   2023          McLaren
7   2023         Mercedes
8   2023  Red Bull Racing
9   2023         Williams
10  2024           Alpine
11  2024     Aston Martin
12  2024          Ferrari
13  2024     Haas F1 Team
14  2024      Kick Sauber
15  2024          McLaren
16  2024         Mercedes
17  2024               RB
18  2024  Red Bull Racing
19  2024         Williams
20  2025           Alpine
21  2025     Aston Martin
22  2025          Ferrari
23  2025     Haas F1 Team
24  2025      Kick Sauber
25  2025          McLaren
26  2025         Mercedes
27  2025     Racing Bulls
28  2025  Red Bull Racing
29  2025         Williams
30  2026           Alpine
31  2026     Aston Martin
32  2026             Audi
33  2026         Cadillac
34  2026          Ferrari
35  2026     Haas F1 Team
36  2026          McLaren
37  2026         Mercedes
38  2026     Racing Bulls
39  2026  Red Bull Racing
40  2026         Williams

In [26]:

def read_warehoused_constructors():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM dim_constructor").df()

    return result

In [27]:
dim_constructors = read_warehoused_constructors()
dim_constructors

    constructor_id  year constructor_name
0                1  2023       Alfa Romeo
1                2  2023       AlphaTauri
2                3  2023           Alpine
3                4  2024           Alpine
4                5  2025           Alpine
5                6  2026           Alpine
6                7  2023     Aston Martin
7                8  2024     Aston Martin
8                9  2025     Aston Martin
9               10  2026     Aston Martin
10              11  2026             Audi
11              12  2026         Cadillac
12              13  2023          Ferrari
13              14  2024          Ferrari
14              15  2025          Ferrari
15              16  2026          Ferrari
16              17  2023     Haas F1 Team
17              18  2024     Haas F1 Team
18              19  2025     Haas F1 Team
19              20  2026     Haas F1 Team
20              21  2024      Kick Sauber
21              22  2025      Kick Sauber
22              23  2023          McLaren
23              24  2024          McLaren
24              25  2025          McLaren
25              26  2026          McLaren
26              27  2023         Mercedes
27              28  2024         Mercedes
28              29  2025         Mercedes
29              30  2026         Mercedes
30              31  2024               RB
31              32  2025     Racing Bulls
32              33  2026     Racing Bulls
33              34  2023  Red Bull Racing
34              35  2024  Red Bull Racing
35              36  2025  Red Bull Racing
36              37  2026  Red Bull Racing
37              38  2023         Williams
38              39  2024         Williams
39              40  2025         Williams
40              41  2026         Williams

### Race

In [28]:
def read_staged_meetings():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM staged_race_meetings_table").df()

    return result

In [29]:
staged_meetings = read_staged_meetings()
staged_meetings

,meeting_key,meeting_name,country_name,circuit_short_name,circuit_type,date_start,date_end,year
0,1141,Bahrain Grand Prix,Bahrain,Sakhir,Permanent,2023-03-03 06:30:00-05:00,2023-03-03 06:30:00-05:00,2023
1,1142,Saudi Arabian Grand Prix,Saudi Arabia,Jeddah,Temporary - Street,2023-03-17 09:30:00-04:00,2023-03-17 09:30:00-04:00,2023
2,1143,Australian Grand Prix,Australia,Melbourne,Temporary - Street,2023-03-30 22:30:00-04:00,2023-03-30 22:30:00-04:00,2023
3,1207,Azerbaijan Grand Prix,Azerbaijan,Baku,Temporary - Street,2023-04-28 05:30:00-04:00,2023-04-28 05:30:00-04:00,2023
4,1208,Miami Grand Prix,United States,Miami,Temporary - Street,2023-05-05 14:00:00-04:00,2023-05-05 14:00:00-04:00,2023
...,...,...,...,...,...,...,...,...
89,1298,Mexico City Grand Prix,Mexico,Mexico City,Permanent,2026-10-30 14:30:00-04:00,2026-10-30 14:30:00-04:00,2026
90,1299,São Paulo Grand Prix,Brazil,Interlagos,Permanent,2026-11-06 10:30:00-05:00,2026-11-06 10:30:00-05:00,2026
91,1300,Las Vegas Grand Prix,United States,Las Vegas,Temporary - Street,2026-11-19 19:30:00-05:00,2026-11-19 19:30:00-05:00,2026
92,1301,Qatar Grand Prix,Qatar,Lusail,Permanent,2026-11-27 08:30:00-05:00,2026-11-27 08:30:00-05:00,2026
93,1302,Abu Dhabi Grand Prix,United Arab Emirates,Yas Marina Circuit,Permanent,2026-12-04 04:30:00-05:00,2026-12-04 04:30:00-05:00,2026

### dim_race

In [30]:
def read_dim_race():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM dim_race").df()

    return result

dim_race = read_dim_race()
dim_race

,race_id,year,race_num,race_name,meeting_key,country_name,circuit_short_name,date_start,date_end,is_sprint_weekend
0,1,2023,1,Bahrain Grand Prix,1141,Bahrain,Sakhir,2023-03-03 06:30:00-05:00,2023-03-03 06:30:00-05:00,False
1,2,2023,2,Saudi Arabian Grand Prix,1142,Saudi Arabia,Jeddah,2023-03-17 09:30:00-04:00,2023-03-17 09:30:00-04:00,False
2,3,2023,3,Australian Grand Prix,1143,Australia,Melbourne,2023-03-30 22:30:00-04:00,2023-03-30 22:30:00-04:00,False
3,4,2023,4,Azerbaijan Grand Prix,1207,Azerbaijan,Baku,2023-04-28 05:30:00-04:00,2023-04-28 05:30:00-04:00,False
4,5,2023,5,Miami Grand Prix,1208,United States,Miami,2023-05-05 14:00:00-04:00,2023-05-05 14:00:00-04:00,False
...,...,...,...,...,...,...,...,...,...,...
89,90,2026,20,Mexico City Grand Prix,1298,Mexico,Mexico City,2026-10-30 14:30:00-04:00,2026-10-30 14:30:00-04:00,False
90,91,2026,21,São Paulo Grand Prix,1299,Brazil,Interlagos,2026-11-06 10:30:00-05:00,2026-11-06 10:30:00-05:00,False
91,92,2026,22,Las Vegas Grand Prix,1300,United States,Las Vegas,2026-11-19 19:30:00-05:00,2026-11-19 19:30:00-05:00,False
92,93,2026,23,Qatar Grand Prix,1301,Qatar,Lusail,2026-11-27 08:30:00-05:00,2026-11-27 08:30:00-05:00,False
93,94,2026,24,Abu Dhabi Grand Prix,1302,United Arab Emirates,Yas Marina Circuit,2026-12-04 04:30:00-05:00,2026-12-04 04:30:00-05:00,False

### Fantasy tables

In [31]:
def read_raw_driver_points():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_driver_points_table").df()

    return result


raw_driver_points = read_raw_driver_points()
raw_driver_points

                 driver  race  points      source_sheet
0        max verstappen     1    35.0  2023DriverPoints
1        lewis hamilton     1    28.0  2023DriverPoints
2       charles leclerc     1    19.0  2023DriverPoints
3          sergio perez     1    -1.0  2023DriverPoints
4        george russell     1    39.0  2023DriverPoints
...                 ...   ...     ...               ...
1671     oliver bearman     4     NaN  2026DriverPoints
1672       esteban ocon     4     NaN  2026DriverPoints
1673    nico hulkenberg     4     NaN  2026DriverPoints
1674        liam lawson     4     NaN  2026DriverPoints
1675  gabriel bortoleto     4     NaN  2026DriverPoints

[1676 rows x 4 columns]

In [32]:
def read_raw_driver_price():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_driver_price_table").df()

    return result


raw_driver_price = read_raw_driver_price()
raw_driver_price

                 driver  race  price     source_sheet
0        max verstappen     1   26.9  2023DriverPrice
1        lewis hamilton     1   23.7  2023DriverPrice
2       charles leclerc     1   21.2  2023DriverPrice
3          sergio perez     1   18.0  2023DriverPrice
4        george russell     1   18.6  2023DriverPrice
...                 ...   ...    ...              ...
1719  gabriel bortoleto     4    5.8  2026DriverPrice
1720     arvid lindblad     4    7.6  2026DriverPrice
1721   franco colapinto     4    7.6  2026DriverPrice
1722       sergio perez     4    7.0  2026DriverPrice
1723     valteri bottas     4    4.1  2026DriverPrice

[1724 rows x 4 columns]

In [33]:
def read_raw_constructor_price():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_constructor_price_table").df()

    return result


raw_constructor_price = read_raw_constructor_price()
raw_constructor_price

         constructor  race  price          source_sheet
0    red bull racing     1   27.2  2023ConstructorPrice
1           mercedes     1   25.1  2023ConstructorPrice
2            ferrari     1   22.1  2023ConstructorPrice
3            mclaren     1    9.1  2023ConstructorPrice
4             alpine     1   10.1  2023ConstructorPrice
..               ...   ...    ...                   ...
739     aston martin     4    8.5  2026ConstructorPrice
740     haas f1 team     4    9.2  2026ConstructorPrice
741             audi     4    5.6  2026ConstructorPrice
742     racing bulls     4    8.1  2026ConstructorPrice
743         cadillac     4    5.0  2026ConstructorPrice

[744 rows x 4 columns]

In [34]:
def read_raw_constructor_points():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM raw_constructor_points_table").df()

    return result


raw_constructor_points = read_raw_constructor_points()
raw_constructor_points

         constructor  race  points           source_sheet
0    red bull racing     1    78.0  2023ConstructorPoints
1           mercedes     1    45.0  2023ConstructorPoints
2            ferrari     1    31.0  2023ConstructorPoints
3            mclaren     1   -16.0  2023ConstructorPoints
4       aston martin     1    56.0  2023ConstructorPoints
..               ...   ...     ...                    ...
739     aston martin     4     NaN  2026ConstructorPoints
740     haas f1 team     4     NaN  2026ConstructorPoints
741             audi     4     NaN  2026ConstructorPoints
742     racing bulls     4     NaN  2026ConstructorPoints
743         cadillac     4     NaN  2026ConstructorPoints

[744 rows x 4 columns]

In [35]:
def read_stage_constructor_points():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM stage_constructor_points_table").df()

    return result


stage_constructor_points = read_stage_constructor_points()
stage_constructor_points

         constructor  race  points  year
0    red bull racing     1    78.0  2023
1           mercedes     1    45.0  2023
2            ferrari     1    31.0  2023
3            mclaren     1   -16.0  2023
4       aston martin     1    56.0  2023
..               ...   ...     ...   ...
728     aston martin     3   -12.0  2026
729     haas f1 team     3    -4.0  2026
730             audi     3    23.0  2026
731     racing bulls     3    18.0  2026
732         cadillac     3     5.0  2026

[733 rows x 4 columns]

In [36]:
def read_stage_constructor_price():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM stage_constructor_price_table").df()

    return result


stage_constructor_price = read_stage_constructor_price()
stage_constructor_price

         constructor  race  price  year
0    red bull racing     1   27.2  2023
1           mercedes     1   25.1  2023
2            ferrari     1   22.1  2023
3            mclaren     1    9.1  2023
4             alpine     1   10.1  2023
..               ...   ...    ...   ...
739     aston martin     4    8.5  2026
740     haas f1 team     4    9.2  2026
741             audi     4    5.6  2026
742     racing bulls     4    8.1  2026
743         cadillac     4    5.0  2026

[744 rows x 4 columns]

In [37]:
def read_stage_driver_price():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM stage_driver_price_table").df()

    return result


stage_driver_price = read_stage_driver_price()
stage_driver_price

                 driver  race  price  year
0        max verstappen     1   26.9  2023
1        lewis hamilton     1   23.7  2023
2       charles leclerc     1   21.2  2023
3          sergio perez     1   18.0  2023
4        george russell     1   18.6  2023
...                 ...   ...    ...   ...
1482  gabriel bortoleto     4    5.8  2026
1483     arvid lindblad     4    7.6  2026
1484   franco colapinto     4    7.6  2026
1485       sergio perez     4    7.0  2026
1486     valteri bottas     4    4.1  2026

[1487 rows x 4 columns]

In [70]:
def read_stage_driver_points():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("SELECT * FROM stage_driver_points_table").df()

    return result


stage_driver_points = read_stage_driver_points()
stage_driver_points

                 driver  race  points  year
0        Max Verstappen     1    35.0  2023
1          Sergio Perez     1    28.0  2023
2        Lewis Hamilton     1    19.0  2023
3          Lando Norris     1    -1.0  2023
4       Fernando Alonso     1    39.0  2023
...                 ...   ...     ...   ...
1460  Gabriel Bortoleto     3     3.0  2026
1461     Arvid Lindblad     3     1.0  2026
1462   Franco Colapinto     3     4.0  2026
1463       Sergio Perez     3     4.0  2026
1464     Valteri Bottas     3     2.0  2026

[1465 rows x 4 columns]

### fact_driver_race testing

# SQL build out testing

In [46]:
def fact_driver_race_testing():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
        result = con.execute("""
            WITH driver_constructor_map AS (
                SELECT DISTINCT
                    meeting_key,
                    full_name,
                    team_name
                FROM staged_session_drivers_table
            )
            SELECT
                r.race_id,
                r.race_name,
                d.driver_id,
                c.constructor_id,
                p.price,
                pts.points AS fantasy_points
            FROM stage_driver_points_table pts
            LEFT JOIN stage_driver_price_table p
                ON pts.year = p.year
               AND pts.race = p.race
               AND pts.driver = p.driver
            LEFT JOIN dim_driver d
                ON pts.driver = d.driver_name
            LEFT JOIN dim_race r
                ON pts.year = r.year
               AND pts.race = r.race_num
            LEFT JOIN driver_constructor_map sd
                ON d.driver_name = sd.full_name
               AND r.meeting_key = sd.meeting_key
            LEFT JOIN dim_constructor c
                ON sd.team_name = c.constructor_name
               AND r.year = c.year
            ORDER BY race_id
        """).df()

    return result

fact_driver_race_test = fact_driver_race_testing()

In [52]:
def making_sure():
    with duckdb.connect(DATABASE_PATH, read_only=True) as con:
            result = con.execute(
            """
            SELECT race_id, driver_id, COUNT(*) AS row_count
            FROM fact_driver_race
            GROUP BY race_id, driver_id
            HAVING COUNT(*) > 1;
            """
        )
    return result

testing_result = making_sure()

CatalogException: Catalog Error: Table with name fact_driver_race does not exist!
Did you mean "raw_drivers_table"?

LINE 3:             FROM fact_driver_race
                         ^

In [49]:
fact_driver_race_test

,race_id,race_name,driver_id,constructor_id,price,fantasy_points
0,1,Bahrain Grand Prix,40,38,4.0,11.0
1,1,Bahrain Grand Prix,35,7,7.5,8.0
2,1,Bahrain Grand Prix,48,2,5.0,8.0
3,1,Bahrain Grand Prix,9,13,17.2,19.0
4,1,Bahrain Grand Prix,43,34,26.9,35.0
...,...,...,...,...,...,...
1460,<NA>,None,<NA>,<NA>,7.7,2.0
1461,<NA>,None,61,<NA>,20.8,22.0
1462,<NA>,None,15,<NA>,13.5,19.0
1463,<NA>,None,55,<NA>,14.5,11.0
1464,<NA>,None,39,<NA>,NaN,0.0

In [50]:
fact_driver_race_test.tail(25)

,race_id,race_name,driver_id,constructor_id,price,fantasy_points
1440,73,Japanese Grand Prix,34,30,23.8,14.0
1441,73,Japanese Grand Prix,39,33,6.9,27.0
1442,73,Japanese Grand Prix,18,6,7.0,43.0
1443,73,Japanese Grand Prix,39,33,6.9,4.0
1444,73,Japanese Grand Prix,<NA>,<NA>,8.8,10.0
1445,<NA>,None,36,<NA>,19.8,32.0
1446,<NA>,None,17,<NA>,15.8,29.0
1447,<NA>,None,10,<NA>,23.5,14.0
1448,<NA>,None,38,<NA>,25.3,30.0
1449,<NA>,None,13,<NA>,5.5,-3.0
1450,<NA>,None,45,<NA>,6.2,4.0
1451,<NA>,None,43,<NA>,30.0,47.0
1452,<NA>,None,52,<NA>,15.4,4.0
1453,<NA>,None,35,<NA>,14.0,21.0
1454,<NA>,None,22,<NA>,20.2,16.0
1455,<NA>,None,33,<NA>,9.6,6.0
1456,<NA>,None,9,<NA>,20.4,4.0
1457,<NA>,None,40,<NA>,5.8,5.0
1458,<NA>,None,<NA>,<NA>,9.6,11.0
1459,<NA>,None,2,<NA>,11.3,10.0
1460,<NA>,None,<NA>,<NA>,7.7,2.0
1461,<NA>,None,61,<NA>,20.8,22.0
1462,<NA>,None,15,<NA>,13.5,19.0
1463,<NA>,None,55,<NA>,14.5,11.0
1464,<NA>,None,39,<NA>,NaN,0.0

In [45]:
fact_driver_race_test.to_csv("testing_fact_driver_race_4_28.csv")